// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfwjwzjrvagtqjtsuqke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmd2p3empydmFndHFqdHN1cWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODcwOTgsImV4cCI6MjA2ODA2MzA5OH0.eYvjISowAJD2Le3ZTVhAkvARFcCFCgHOAUGTTgADT8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});